name: Build and Test Docker Image

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      confirmation:
        description: "Set this to 'true' to manually run."
        required: true
        type: boolean

jobs:
  build:
    runs-on: 
      - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t "sample-app:v1" .

      - name: Run Docker Image
        id: docker-run
        run: |
          docker_output=$(docker run "sample-app:v1")
          echo $docker_output
          echo "docker_output=$docker_output" >> $GITHUB_OUTPUT

      - name: Test Docker Image
        shell: bash
        env:
          docker_output: ${{ steps.docker-run.outputs.docker_output }}
        run: |
          if [[ "$docker_output" == "*Hello World!*" ]]
          then
            echo "Docker Build Completed"
          else
            echo "Docker Build Failed"
            exit 1
          fi
